* PYTHON SCRIPTS

** DEPENDENCIES
linux dependencies
    - figlet     

*** install with your linux pkg manager:
#+BEGIN_SRC bash
sudo apt install figlet -y
#+END_SRC

python dependencies
    - Selenium
    #+BEGIN_SRC bash
    pip install selenium
    #+END_SRC
    - BeautifulSoup
    #+BEGIN_SRC bash
    pip install bs4
    #+END_SRC
- Chromedriver (use sudo)
    #+BEGIN_SRC bash
    sudo pip install chromedriver
    #+END_SRC

** DOWNLOAD CODE TO YOUR MACHINE
Open your linux cmd line, navigate to home folder.. probably already there by default.
Make sure you have git as well as the listed dependencies installed and copy and paste the following command

#+BEGIN_SRC bash
cd $HOME
git clone https://github.com/jc9361/scripts_for_matt.git
#+END_SRC
    
** repo_maker
(run with "python3 /scripts_for_matt/repo_maker/main.py")
This script uses python and selenium to open your browser (chrome) and 
automates the process of loging in, clicking create repo, repo naming,
and linking it to a local folder on your system.
    
    
** get_latest_arch 

This script uses python and selenium to open yor Chrome and navigate to "https://archlinux.org".
From there it will download the latest ISO torrent, open the torrent in your bittorrent client,
"transmission-cli". When the torrent is finished downloading the script will ask you if you would
like to burn it to a disk and for you to provide the location of that disk, ie; "/dev/sdd"
    
 run script..
#+BEGIN_SRC bash
python3 $HOME/scripts_for_matt/get_latest_arch/main.py
#+END_SRC
   


** covid 

This script uses pythong and BeautifulSoup to parse "https://worldometers.info" and display 
current covid stats for the US and WORLD in a clean and easy to read format... right inside the terminal.

run script..
#+BEGIN_SRC bash
python3 $HOME/scripts_for_matt/covid/main.py
#+END_SRC
   



* BASH SCRIPTS

** DEPENDENCIES
        awk
        sed

        Check to if you have these installed... you probably do.
        #+BEGIN_SRC bash
        which awk
        which sed
        #+END_SRC


        if nothing was returned on the las command you need to install them, use your package manager
        #+BEGIN_SRC bash
        sudo apt install awk sed -y
        #+END_SRC

        Give scripts permission to run...
        #+BEGIN_SRC bash
        chmod +x $HOME/scripts_for_matt/bash_scripts/awk.sh
        chmod +x $HOME/scripts_for_matt/bash_scripts/sed.sh
        #+END_SRC

        Run scripts..
        #+begin_src bash
        $HOME/scripts_for_matt/bash_scripts/awk.sh
        $HOME/scripts_for_matt/bash_scripts/sed.sh
        #+end_src

        or..

        #+begin_src bash
        cd $HOME/scripts_for_matt/bash_scripts
        ./awk.sh
        ./sed.sh
        #+end_src

        
